models:
- name: PaddleOCR
  displayName: PaddleOCR
  modelHubID: paddleocr
  category: Optical Character Recognition
  type: NGC
  description: PaddleOCR is an ultra lightweight Optical Character Recognition (OCR) system by Baidu. PaddleOCR supports a variety of cutting-edge algorithms related to OCR.
  requireLicense: true
  licenseAgreements:
  - label: Use Policy
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-community-models-license/
  - label: License Agreement
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-software-license-agreement/
  modelVariants:
  - variantId: PaddleOCR
    source:
      URL: https://catalog.ngc.nvidia.com/orgs/nim/teams/baidu/containers/paddleocr
    optimizationProfiles:
    - profileId: nim/baidu/paddleocr:l40sx1-trt-fp16-evboykuf0g
      framework: TensorRT-LLM
      displayName: Paddleocr NVIDIA L40Sx1 FP16
      ngcMetadata:
        631c6b6c76996d8cc04cf7cfde63d15d1b5f57cb323dc129f2a838b35703f1d9:
          model: baidu/paddleocr
          release: 1.5.0
          tags:
            backend: triton
            batch_size: '32'
            device_id: 26b9:10de
            gpu: NVIDIA L40S
            gpu_key: l40s
            model_type: tensorrt
            precision: fp16
      modelFormat: trt-llm
      spec:
      - key: PRECISION
        value: FP16
      - key: GPU
        value: L40S
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.5.0
      - key: DOWNLOAD SIZE
        value: 1GB
      - key: BACKEND
        value: TRITON
      - key: MODEL TYPE
        value: TENSORRT
    - profileId: nim/baidu/paddleocr:a10gx1-trt-fp16-ijpjeptpna
      framework: TensorRT-LLM
      displayName: Paddleocr NVIDIA A10Gx1 FP16
      ngcMetadata:
        acba2841622c4da2050811e8c7c4bae4c16996ab61b67d68b089176524d70383:
          model: baidu/paddleocr
          release: 1.5.0
          tags:
            backend: triton
            batch_size: '32'
            device_id: 2237:10de
            gpu: NVIDIA A10G
            gpu_key: a10g
            model_type: tensorrt
            precision: fp16
      modelFormat: trt-llm
      spec:
      - key: PRECISION
        value: FP16
      - key: GPU
        value: A10G
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.5.0
      - key: DOWNLOAD SIZE
        value: 1GB
      - key: BACKEND
        value: TRITON
      - key: MODEL TYPE
        value: TENSORRT
    - profileId: nim/baidu/paddleocr:4_ONNX_python_2
      framework: ONNX
      displayName: Paddleocr ONNX FP16
      ngcMetadata:
        edc693c6fccd68d266622eace04225421e353d7ce31e3b207afc5ff35124127b:
          model: baidu/paddleocr
          release: 1.5.0
          tags:
            backend: triton
            model_type: onnx
            precision: fp16
      modelFormat: onnx
      spec:
      - key: PRECISION
        value: FP16
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.5.0
      - key: DOWNLOAD SIZE
        value: 1GB
      - key: BACKEND
        value: TRITON
      - key: MODEL TYPE
        value: ONNX
  labels:
  - signed images
  - NSPECT-LDAL-INWI
  - NVIDIA AI Enterprise Supported
  - NVIDIA NIM
  config:
    architectures:
    - Other
    modelType: NIM
  license: NVIDIA AI Foundation Models Community License
