models:
- name: PaddleOCR
  displayName: PaddleOCR
  modelHubID: paddleocr
  category: Optical Character Recognition
  type: NGC
  description: PaddleOCR is an ultra lightweight Optical Character Recognition (OCR) system by Baidu. PaddleOCR supports a variety of cutting-edge algorithms related to OCR.
  requireLicense: true
  licenseAgreements:
  - label: Use Policy
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-community-models-license/
  - label: License Agreement
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-software-license-agreement/
  modelVariants:
  - variantId: PaddleOCR
    source:
      URL: https://catalog.ngc.nvidia.com/orgs/nim/teams/baidu/containers/paddleocr
    optimizationProfiles:
    - profileId: nim/baidu/paddleocr:a10gx1-trt-fp16-ijpjeptpna
      framework: TensorRT-LLM
      displayName: Paddleocr A10Gx1 FP16
      ngcMetadata:
        859ace730c899fb7b8362fe773639da57544f87584f9ed138089e85665653972:
          model: baidu/paddleocr
          release: 1.4.0
          tags:
            backend: triton
            batch_size: '32'
            gpu: A10G
            model_type: tensorrt
            precision: fp16
      modelFormat: trt-llm
      spec:
      - key: PRECISION
        value: FP16
      - key: GPU
        value: A10G
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.4.0
      - key: DOWNLOAD SIZE
        value: 1GB
    - profileId: nim/baidu/paddleocr:l40sx1-trt-fp16-evboykuf0g
      framework: TensorRT-LLM
      displayName: Paddleocr L40Sx1 FP16
      ngcMetadata:
        90699b066c264c9533628aeb4f1814ef51e0f2f021540e3ae77181f2ef9ce9ed:
          model: baidu/paddleocr
          release: 1.4.0
          tags:
            backend: triton
            batch_size: '32'
            gpu: L40S
            model_type: tensorrt
            precision: fp16
      modelFormat: trt-llm
      spec:
      - key: PRECISION
        value: FP16
      - key: GPU
        value: L40S
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.4.0
      - key: DOWNLOAD SIZE
        value: 1GB
  labels:
  - signed images
  - NSPECT-LDAL-INWI
  - NVIDIA AI Enterprise Supported
  - NVIDIA NIM
  config:
    architectures:
    - Other
    modelType: NIM
  license: NVIDIA AI Foundation Models Community License
