models:
- name: Nemoretriever Graphic Elements V1
  displayName: Nemoretriever Graphic Elements V1
  modelHubID: nemoretriever-graphic-elements-v1
  category: Object Detection
  type: NGC
  description: NVIDIA NeMo Retriever NIM for graphic elements v1 is a fine-tuned object detection model, trained specifically for detecting the elements of charts and tables in documents
  requireLicense: true
  licenseAgreements:
  - label: Use Policy
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-community-models-license/
  - label: License Agreement
    url: https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-software-license-agreement/
  modelVariants:
  - variantId: Nemoretriever Graphic Elements V1
    source:
      URL: https://catalog.ngc.nvidia.com/orgs/nim/teams/nvidia/containers/nemoretriever-graphic-elements-v1
    optimizationProfiles:
    - profileId: nim/nvidia/nemoretriever-graphic-elements-v1:a10gx1-trt-fp16-ge6bpqew8g
      framework: TensorRT-LLM
      displayName: Nemoretriever Graphic Elements V1 A10Gx1 FP16
      ngcMetadata:
        859ace730c899fb7b8362fe773639da57544f87584f9ed138089e85665653972:
          model: nvidia/nemoretriever-graphic-elements-v1
          release: 1.3.0
          tags:
            backend: triton
            batch_size: '32'
            gpu: A10G
            model_type: tensorrt
            precision: fp16
            tp: '1'
      modelFormat: trt-llm
      spec:
      - key: PRECISION
        value: FP16
      - key: GPU
        value: A10G
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 1GB
      - key: BACKEND
        value: TRITON
      - key: MODEL TYPE
        value: TENSORRT
    - profileId: nim/nvidia/nemoretriever-graphic-elements-v1:l40sx1-trt-fp16-ltjamioamw
      framework: TensorRT-LLM
      displayName: Nemoretriever Graphic Elements V1 L40Sx1 FP16
      ngcMetadata:
        90699b066c264c9533628aeb4f1814ef51e0f2f021540e3ae77181f2ef9ce9ed:
          model: nvidia/nemoretriever-graphic-elements-v1
          release: 1.3.0
          tags:
            backend: triton
            batch_size: '32'
            gpu: L40S
            model_type: tensorrt
            precision: fp16
            tp: '1'
      modelFormat: trt-llm
      spec:
      - key: PRECISION
        value: FP16
      - key: GPU
        value: L40S
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 1GB
      - key: BACKEND
        value: TRITON
      - key: MODEL TYPE
        value: TENSORRT
    - profileId: nim/nvidia/nemoretriever-graphic-elements-v1:2_ONNX_FP16_1024
      framework: ONNX
      displayName: Nemoretriever Graphic Elements V1 ONNX FP16
      ngcMetadata:
        edc693c6fccd68d266622eace04225421e353d7ce31e3b207afc5ff35124127b:
          model: nvidia/nemoretriever-graphic-elements-v1
          release: 1.3.0
          tags:
            backend: triton
            model_type: onnx
            precision: fp16
            tp: '1'
      modelFormat: onnx
      spec:
      - key: PRECISION
        value: FP16
      - key: COUNT
        value: 1
      - key: NIM VERSION
        value: 1.3.0
      - key: DOWNLOAD SIZE
        value: 1GB
      - key: BACKEND
        value: TRITON
      - key: MODEL TYPE
        value: ONNX
  labels:
  - signed images
  - NVIDIA AI Enterprise Supported
  - NVIDIA NIM
  - NSPECT-7OBP-T77C
  config:
    architectures:
    - Other
    modelType: NGC
  license: NVIDIA AI Foundation Models Community License
